import { test, expect } from '@playwright/test';

test('addItem', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Log in' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Google logoSign in with google' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('button', { name: 'Add new account' }).click();
  await page1.getByRole('button', { name: 'Auto-generate user information' }).click();
  await page1.getByRole('button', { name: 'Sign in with Google.com' }).click();
  await page.getByRole('button', { name: '+' }).click();
  await page.getByRole('textbox', { name: 'Enter Watchlist Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Watchlist Name' }).fill('My watchlist');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('link', { name: 'My watchlist' }).click();
  await page.getByRole('button', { name: '+' }).click();
  await page.getByRole('textbox', { name: 'Trailer link' }).click();
  await page.getByRole('textbox', { name: 'Trailer link' }).fill('https://www.youtube.com/watch?v=9OAC55UWAQs');
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill('Lilo & Stitch');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('A lonely Hawaiian girl befriends a runaway alien, helping to mend her fragmented family.');
  await page.getByRole('textbox', { name: 'Director' }).click();
  await page.getByRole('textbox', { name: 'Director' }).fill(' Dean Fleischer Camp');
  await page.getByText('Create a watchlist entryTitleTypeMovieTelevision ShowOtherDescriptionA lonely').click();
  await page.getByLabel('MPA Rating').selectOption('pg');
  await page.getByRole('textbox', { name: 'Genre Tags' }).click();
  await page.getByRole('textbox', { name: 'Genre Tags' }).fill('fa');
  await page.getByText('Family', { exact: true }).click();
  await page.locator('#item-genre').nth(1).click();
  await page.locator('#item-genre').nth(1).fill('stupid');
  await page.getByText('+ Add as new Tag').click();
  await page.getByRole('spinbutton', { name: 'Release year' }).click();
  await page.getByRole('spinbutton', { name: 'Release year' }).fill('2025');
  await page.getByRole('spinbutton', { name: 'Release year' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Length (in minutes)' }).fill('108');
  await page.getByRole('spinbutton', { name: 'Length (in minutes)' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'IMDB rating' }).fill('6.9');
  await page.getByRole('spinbutton', { name: 'IMDB rating' }).press('Tab');
  await page.getByRole('textbox', { name: 'IMDB link' }).fill('https://www.imdb.com/title/tt11655566/?ref_=nv_sr_srsg_1_tt_7_nm_0_in_0_q_lilo%2520a');
  await page.getByRole('textbox', { name: 'IMDB link' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
});
